// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskInsightEngine.Infrastructure.Persistence;

#nullable disable

namespace TaskInsightEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508183313_RiskSubscription")]
    partial class RiskSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskAssignmentTaskImpediment", b =>
                {
                    b.Property<int>("TaskAssignmentsTaskAssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskImpedimentsTaskImpedimentId")
                        .HasColumnType("integer");

                    b.HasKey("TaskAssignmentsTaskAssignmentId", "TaskImpedimentsTaskImpedimentId");

                    b.HasIndex("TaskImpedimentsTaskImpedimentId");

                    b.ToTable("TaskAssignmentTaskImpediment");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.BriefingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttentionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecoveringCount")
                        .HasColumnType("integer");

                    b.Property<int>("SilentCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttentionCount");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecoveringCount");

                    b.HasIndex("SilentCount");

                    b.ToTable("briefing", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.DailyTaskUpdateStatus", b =>
                {
                    b.Property<int>("DailyTaskUpdateStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyTaskUpdateStatusId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EffortHours")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UpdatedEta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DailyTaskUpdateStatusId");

                    b.HasIndex("ProjectMemberId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("dailyTaskUpdateStatus", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("PriorityId");

                    b.ToTable("prioritys", (string)null);

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            Type = "Low"
                        },
                        new
                        {
                            PriorityId = 2,
                            Type = "Medium"
                        },
                        new
                        {
                            PriorityId = 3,
                            Type = "High"
                        });
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ProjectId");

                    b.HasIndex("PriorityId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectMemberId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("projectmembers", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Risk", b =>
                {
                    b.Property<int>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiskId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("RiskId");

                    b.ToTable("risk", (string)null);

                    b.HasData(
                        new
                        {
                            RiskId = 1,
                            Description = "Blocked by third-party/vendor or external system",
                            Name = "External Dependency",
                            Weight = 3
                        },
                        new
                        {
                            RiskId = 2,
                            Description = "Blocked due to internal team dependency or issue",
                            Name = "Internal Blocker",
                            Weight = 2
                        },
                        new
                        {
                            RiskId = 3,
                            Description = "Insufficient resources or bandwidth",
                            Name = "Resource Constraint",
                            Weight = 3
                        },
                        new
                        {
                            RiskId = 4,
                            Description = "Unknown technical challenges or complexity",
                            Name = "Technical Uncertainty",
                            Weight = 4
                        },
                        new
                        {
                            RiskId = 5,
                            Description = "Unclear or changing requirements",
                            Name = "Requirement Gap",
                            Weight = 5
                        });
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.RiskSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Delta")
                        .HasColumnType("integer");

                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<string>("PrevLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrevScore")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TopReasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Date", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_RiskSnapshot_TaskId_Date_Id");

                    b.ToTable("risksnapshot", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.RiskSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail", "ProjectId")
                        .IsUnique();

                    b.ToTable("RiskSubscriptions");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "ProjectManager"
                        });
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("status", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Type = "New"
                        },
                        new
                        {
                            StatusId = 2,
                            Type = "Completed"
                        },
                        new
                        {
                            StatusId = 3,
                            Type = "InProgress"
                        },
                        new
                        {
                            StatusId = 4,
                            Type = "OnHold"
                        },
                        new
                        {
                            StatusId = 5,
                            Type = "InReview"
                        },
                        new
                        {
                            StatusId = 6,
                            Type = "Blocked"
                        });
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskAssignmentId"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.HasKey("TaskAssignmentId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssignerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("taskAssignment", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskImpediment", b =>
                {
                    b.Property<int>("TaskImpedimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskImpedimentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolvedBy")
                        .HasColumnType("integer");

                    b.Property<int>("RiskId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TaskImpedimentId");

                    b.HasIndex("RiskId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("taskimpediment", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskImpedimentComment", b =>
                {
                    b.Property<int>("TaskImpedimentCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskImpedimentCommentId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("TaskImpedimentId")
                        .HasColumnType("integer");

                    b.HasKey("TaskImpedimentCommentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TaskImpedimentId");

                    b.ToTable("taskimpedimentcomment", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpectedETA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TaskItemId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProjectId");

                    b.ToTable("taskItem", (string)null);
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaskAssignmentTaskImpediment", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskAssignment", null)
                        .WithMany()
                        .HasForeignKey("TaskAssignmentsTaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskImpediment", null)
                        .WithMany()
                        .HasForeignKey("TaskImpedimentsTaskImpedimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.BriefingEntry", b =>
                {
                    b.OwnsOne("TaskInsightEngine.Domain.Entities.BriefingSnapshot", "BriefingSnapshot", b1 =>
                        {
                            b1.Property<int>("BriefingEntryId")
                                .HasColumnType("integer");

                            b1.HasKey("BriefingEntryId");

                            b1.ToTable("briefing");

                            b1
                                .ToJson("BriefingSnapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BriefingEntryId");

                            b1.OwnsMany("TaskInsightEngine.Domain.Entities.BriefingItem", "NeedsAttention", b2 =>
                                {
                                    b2.Property<int>("BriefingSnapshotBriefingEntryId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("AssigneeId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Delta")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Level")
                                        .HasColumnType("text");

                                    b2.Property<string>("Movement")
                                        .HasColumnType("text");

                                    b2.Property<int>("ProjectId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Score")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TaskId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<string>("TopReasons")
                                        .HasColumnType("text");

                                    b2.HasKey("BriefingSnapshotBriefingEntryId", "__synthesizedOrdinal");

                                    b2.ToTable("briefing");

                                    b2.WithOwner()
                                        .HasForeignKey("BriefingSnapshotBriefingEntryId");
                                });

                            b1.OwnsMany("TaskInsightEngine.Domain.Entities.BriefingItem", "Recovering", b2 =>
                                {
                                    b2.Property<int>("BriefingSnapshotBriefingEntryId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("AssigneeId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Delta")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Level")
                                        .HasColumnType("text");

                                    b2.Property<string>("Movement")
                                        .HasColumnType("text");

                                    b2.Property<int>("ProjectId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Score")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TaskId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<string>("TopReasons")
                                        .HasColumnType("text");

                                    b2.HasKey("BriefingSnapshotBriefingEntryId", "__synthesizedOrdinal");

                                    b2.ToTable("briefing");

                                    b2.WithOwner()
                                        .HasForeignKey("BriefingSnapshotBriefingEntryId");
                                });

                            b1.OwnsMany("TaskInsightEngine.Domain.Entities.BriefingItem", "SlientRisk", b2 =>
                                {
                                    b2.Property<int>("BriefingSnapshotBriefingEntryId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("AssigneeId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Delta")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Level")
                                        .HasColumnType("text");

                                    b2.Property<string>("Movement")
                                        .HasColumnType("text");

                                    b2.Property<int>("ProjectId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("Score")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TaskId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<string>("TopReasons")
                                        .HasColumnType("text");

                                    b2.HasKey("BriefingSnapshotBriefingEntryId", "__synthesizedOrdinal");

                                    b2.ToTable("briefing");

                                    b2.WithOwner()
                                        .HasForeignKey("BriefingSnapshotBriefingEntryId");
                                });

                            b1.Navigation("NeedsAttention");

                            b1.Navigation("Recovering");

                            b1.Navigation("SlientRisk");
                        });

                    b.Navigation("BriefingSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.DailyTaskUpdateStatus", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.ProjectMember", "ProjectMember")
                        .WithMany("DailyTaskUpdateStatus")
                        .HasForeignKey("ProjectMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("DailyTaskUpdateStatuses")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMember");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Project", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.User", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.RiskSnapshot", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("RiskSnapshots")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskAssignment", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.ProjectMember", "AssigneeMember")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.ProjectMember", "AssignerMember")
                        .WithMany()
                        .HasForeignKey("AssignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.ProjectMember", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskAssignment")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssigneeMember");

                    b.Navigation("AssignerMember");

                    b.Navigation("Manager");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskImpediment", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskImpediments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskImpedimentComment", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.ProjectMember", "Member")
                        .WithMany("TaskImpedimentComments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.TaskImpediment", "TaskImpediment")
                        .WithMany("TaskImpedimentComments")
                        .HasForeignKey("TaskImpedimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("TaskImpediment");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.Priority", null)
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskInsightEngine.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.User", b =>
                {
                    b.HasOne("TaskInsightEngine.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.ProjectMember", b =>
                {
                    b.Navigation("DailyTaskUpdateStatus");

                    b.Navigation("TaskImpedimentComments");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskImpediment", b =>
                {
                    b.Navigation("TaskImpedimentComments");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("DailyTaskUpdateStatuses");

                    b.Navigation("RiskSnapshots");

                    b.Navigation("TaskAssignment");

                    b.Navigation("TaskImpediments");
                });

            modelBuilder.Entity("TaskInsightEngine.Domain.Entities.User", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
